Repository CS2113-AY1819S2-T08-4/main, pull requests merged in 2019-04, with the labels that each got.

#86 View and edit group and house
  src/main/java/seedu/address/logic/commands/AddHouseCommand.java
  src/main/java/seedu/address/logic/commands/EditGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditHouseCommand.java
  src/main/java/seedu/address/logic/commands/ViewGroupsCommand.java
  src/main/java/seedu/address/logic/commands/ViewHousesCommand.java
  src/main/java/seedu/address/logic/parser/AddGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/AddHouseCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/EditHouseCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleParticipantsUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#95 Delete group house commands
  src/main/java/seedu/address/logic/commands/AddHouseCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteHouseCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteHouseCommandParser.java
Labels: priority.High

#96 Size command
  src/main/java/seedu/address/logic/commands/SizeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium

#94 Implementation of randomization
  src/main/java/seedu/address/logic/commands/RandomizeCommand.java
  src/main/java/seedu/address/logic/parser/RandomizeCommandParser.java
  src/test/java/seedu/address/logic/parser/RandomizeCommandParserTest.java
Labels: priority.High, type.Story

#104 Updating of documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/weizhang05.adoc
  docs/templates/_header.html.slim
Labels: priority.High, type.Docs

#105 More updates on documentation
  docs/UserGuide.adoc
  docs/team/weizhang05.adoc
Labels: priority.High, type.Docs

#110 Updating Clyde PPP
  build.gradle
  docs/team/weizhang05.adoc
  docs/templates/_header.html.slim
Labels: priority.High, type.Docs

#97 Export command
  build.gradle
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/WriteToExcel.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.Medium, type.Epic

#111 Clear command box
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: priority.Medium, type.Task

#121 Solve issues for bday and phone validity, update user guide
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/UiLabelledParts.png
  docs/images/damithc.jpg
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
  src/main/java/seedu/address/model/participant/Birthday.java
  src/main/java/seedu/address/model/participant/Phone.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.Medium

#141 House name update and adding listhouse command
  FOP_MANAGER_LIST.xls
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddOglCommand.java
  src/main/java/seedu/address/logic/commands/AddParticipantCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditHouseCommand.java
  src/main/java/seedu/address/logic/commands/ListHouseCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListHouseCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/grouping/FindHousePredicate.java
  src/main/java/seedu/address/model/grouping/Group.java
  src/main/java/seedu/address/model/grouping/UniqueGroupList.java
  src/main/java/seedu/address/storage/JsonAdaptedParticipant.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedParticipantTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.Medium

#149 Docs updates
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ImportCommandActivityDiagram.pptx
  docs/diagrams/ImportCommandSequenceDiagram.pptx
  docs/images/ExportImage.png
  docs/images/ExportResult.png
  docs/images/ImportCommandActivityDiagram.png
  docs/images/ImportCommandSequenceDiagram.png
  docs/team/ssunil3232.adoc
Labels: type.Docs

#150 PPP update
  docs/UserGuide.adoc
  docs/team/shanseet.adoc
Labels: type.Docs

#154 Fixing of minor bugs
  src/main/java/seedu/address/commons/Value.java
  src/main/java/seedu/address/model/participant/Birthday.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, severity.High, type.Bug

#156 Addtional optimizing and cleaning of randomize algo
  src/main/java/seedu/address/logic/commands/RandomizeCommand.java
Labels: priority.High, type.Enhancement

#157 Update docs
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/AddGroupSequenceDiagram.png
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.Docs

#159 Updating of documentation
  FOP_MANAGER_FRESHMEN_LIST.xls
  FOP_MANAGER_LIST.xls
  FOP_MANAGER_OGL_LIST.xls
  README.adoc
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/RandomizeSequenceDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/RandomizeActivityDiagram.png
  docs/images/RandomizeSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/randomize_fail.png
  docs/images/randomize_success.png
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: priority.High, status.Ongoing, type.Docs

#171 More documentation updates
  README.adoc
  docs/team/weizhang05.adoc
Labels: priority.High, type.Docs

#172 Updated PPP
  docs/team/weizhang05.adoc
Labels: priority.High, type.Docs
