Repository CS2113-AY1819S2-T08-4/main, pull requests merged in 2019-03, with the labels that each got.

#51 Update of the ContactUs
  docs/ContactUs.adoc
Labels: type.Task

#52 Add Participant Command
  src/main/java/seedu/address/logic/commands/AddParticipantCommand.java
  src/main/java/seedu/address/logic/parser/AddParticipantCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/FreshmanList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#37 "Randomize" further implementation
  src/main/java/seedu/address/logic/commands/RandomizeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RandomizeCommandParser.java
  src/test/java/seedu/address/logic/commands/RandomizeCommandTest.java
  src/test/java/seedu/address/logic/parser/RandomizeCommandParserTest.java
Labels: priority.High, type.Enhancement

#68 Initial update of web template
  AboutUs.html
  ContactUs.html
  DeveloperGuide.html
  HelpWindow.html
  LearningOutcomes.html
  UserGuide.html
  UsingAppVeyor.html
  UsingCheckstyle.html
  UsingCoveralls.html
  UsingGradle.html
  UsingNetlify.html
  UsingTravis.html
  index.html
  team/shanseet.html
  team/ssunil3232.html
  team/tantantan277.html
  team/weizhang05.html
Labels: type.Task

#74 Update User Guide
  docs/UserGuide.adoc
Labels: type.Docs

#21 View undo and redo list in GUI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RedoCard.java
  src/main/java/seedu/address/ui/RedoListPanel.java
  src/main/java/seedu/address/ui/UndoCard.java
  src/main/java/seedu/address/ui/UndoListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/RedoListCard.fxml
  src/main/resources/view/RedoListPanel.fxml
  src/main/resources/view/UndoListCard.fxml
  src/main/resources/view/UndoListPanel.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.Medium, type.Task

#63 Update DeveloperGuide for Export Feature
  docs/DeveloperGuide.adoc
Labels: status.Ongoing, type.Docs

#55 List freshmen command
  src/main/java/seedu/address/logic/commands/ListParticipantCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/FreshmanList.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.Medium

#81 List OGL command updated
  src/main/java/seedu/address/logic/commands/AddOglCommand.java
  src/main/java/seedu/address/logic/commands/ListOglCommand.java
  src/main/java/seedu/address/logic/commands/ListParticipantCommand.java
  src/main/java/seedu/address/logic/parser/AddOglCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListOglCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/FindingOglPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/OglList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium

#83 Solve Conflicts to ListParticipant Command
  src/main/java/seedu/address/logic/commands/AddOglCommand.java
  src/main/java/seedu/address/logic/commands/ListParticipantCommand.java
  src/main/java/seedu/address/logic/parser/AddParticipantCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListParticipantCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/participant/Person.java
  src/main/java/seedu/address/model/person/FindingParticipantPredicate.java
Labels: priority.Medium

#87 Update to User Guide adoc
  docs/UserGuide.adoc
Labels: type.Docs

#85 Updating add and edit commands to accept empty group, and reject nonexistent groups
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/AddOglCommand.java
  src/main/java/seedu/address/logic/commands/AddParticipantCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/grouping/Group.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.High
